#!/usr/bin/env python3
"""Generate the paper's figures, as pgfplots/TikZ, from saved results.

The companion of make_tables.py: nothing here is drawn by hand, so a figure
cannot drift from the results behind it. Each figure writes its own data files
and a self-contained `figure` environment the paper `\\input`s.

    python3 scripts/make_figures.py                      # both, into ./figures and ./plots
    python3 scripts/make_figures.py --out <paper dir>    # write beside the paper
    python3 scripts/make_figures.py --figure bounds

  bounds       per-instance bounds + performance profile of the lower bound
  convergence  upper-bound trajectories over cutting-plane iterations, m = 5

Captions here are deliberately short and descriptive; findings belong in the
section that discusses the figure, not in its caption.

Colours are the four categorical slots validated for colour-vision deficiency
(worst all-pairs Delta E 9.2 under deuteranopia); marker shape and line style
repeat that distinction, so identity never rests on hue alone.
"""
import argparse, csv, math, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tables.common import (ROOT, load_instances, load_result,  # noqa: E402
                           display_name)

PALETTE = [("sOne", "2A78D6"), ("sTwo", "EB6834"),
           ("sThree", "4A3AA7"), ("sFour", "1BAF7A")]

PREAMBLE = r"""\pgfplotsset{
  vizbase/.style={
    width=0.86\textwidth,
    tick label style={font=\scriptsize}, label style={font=\footnotesize},
    axis line style={gray!55, line width=0.3pt},
    tick style={gray!55, line width=0.3pt},
    ymajorgrids, grid style={gray!20, line width=0.2pt},
    legend style={font=\scriptsize, draw=none, fill=none,
                  at={(0.5,1.02)}, anchor=south, legend columns=-1,
                  /tikz/every even column/.append style={column sep=7pt}},
  }
}
"""


def colours():
    return "".join(f"\\definecolor{{{n}}}{{HTML}}{{{h}}}" + ("\n" if i % 2 else "")
                   for i, (n, h) in enumerate(PALETTE))


def short(name):
    """GHZ_5_2 -> G_5, Dicke_5_1 -> D_{5,1}, Cluster_4 -> C_4."""
    p = name.split("_")
    if p[0] == "GHZ":
        return f"$\\mathrm{{G}}_{{{p[1]}}}$"
    if p[0] == "Cluster":
        return f"$\\mathrm{{C}}_{{{p[1]}}}$"
    return f"$\\mathrm{{D}}_{{{p[1]},{p[2]}}}$"


# --------------------------------------------------------------------------
def fig_bounds(out, data):
    inst = load_instances(os.path.join(ROOT, "benchmark"))
    # same ordering as the tables (Context.states): by subsystem count, then
    # display name -- the caption says the figure follows the tables, so it must
    order = sorted(inst.items(), key=lambda kv: (kv[1][1], display_name(kv[1][0])))
    dirs = [os.path.join(ROOT, "results", "main")]
    rows, labels = [], []
    for st, (name, m) in order:
        g = lambda a, k: (load_result(dirs, st, a) or {}).get(k)
        ubs = [v for v in (g("Alt-SDP", "glbub"), g("CP", "glbub"), g("IR", "glbub"))
               if v and math.isfinite(v) and v > 0]
        lbs = {a: g(a, "glblb") for a in ("CP", "IR", "DPS", "DDPS+")}
        lbs = {a: v for a, v in lbs.items() if v is not None and math.isfinite(v)}
        if not ubs or not lbs:
            continue
        rows.append((len(rows), min(ubs), max(lbs.values()), lbs.get("CP"), lbs.get("DPS")))
        labels.append(short(name))
    path = os.path.join(data, "bounds_by_instance.dat")
    with open(path, "w") as fh:
        fh.write("# idx best_ub best_lb cp_lb dps_lb\n")
        for i, bu, bl, cp, dps in rows:
            fh.write(f"{i} {bu:.5f} {bl:.5f} {cp:.5f} {dps:.5f}\n")

    marks = [("*", 2.3, "sOne"), ("square*", 2.2, "sTwo"),
             ("triangle*", 2.8, "sThree"), ("diamond*", 2.6, "sFour")]
    series = "\n".join(
        f"\\addplot[only marks, mark={mk}, mark size={sz}pt, {c},\n"
        f"         mark options={{draw=white, line width=0.5pt, fill={c}}}]\n"
        f"  table[x index=0, y index={k}] {{plots/bounds_by_instance.dat}};"
        for k, (mk, sz, c) in enumerate(marks, start=1))

    tex = f"""% generated by scripts/make_figures.py -- do not edit by hand
\\begin{{figure}}[tbp]
\\centering
{PREAMBLE}{colours()}
\\begin{{subfigure}}{{\\textwidth}}\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[vizbase, height=4.3cm,
  ylabel={{bounds on $\\opt$}}, ymin=-0.04, ymax=1.02, ytick={{0,0.25,0.5,0.75,1.0}},
  xmin=-0.6, xmax={len(rows) - 0.4}, xtick={{0,...,{len(rows) - 1}}},
  xticklabels={{{','.join(labels)}}},
  xticklabel style={{font=\\scriptsize}},
]
{series}
\\legend{{$\\ub_{{\\relx}}$ (IR), $\\lb_{{\\relx}}$ (DDPS+), $\\lb_{{\\relx}}$ (CP), $\\lb_{{\\relx}}$ (DPS)}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{}}\\label{{fig.bounds.inst}}
\\end{{subfigure}}

\\vspace{{0.8em}}

\\begin{{subfigure}}{{\\textwidth}}\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[vizbase, height=4.1cm,
  xlabel={{factor of the best lower bound}},
  ylabel={{fraction of instances}},
  xmin=1, xmax=3, ymin=-0.04, ymax=1.09,
  xtick={{1,1.5,2,2.5,3}}, minor xtick={{1.25,1.75,2.25,2.75}},
  ytick={{0,0.25,0.5,0.75,1.0}},
  every axis plot/.append style={{mark=none, line width=1.1pt, const plot}},
]
\\addplot[sTwo]           table[x index=0, y index=6] {{plots/profile_lb.dat}};
\\addplot[sThree, dashed] table[x index=0, y index=3] {{plots/profile_lb.dat}};
\\addplot[sFour, dash pattern=on 1pt off 2pt, line width=1.4pt]
                         table[x index=0, y index=4] {{plots/profile_lb.dat}};
\\legend{{DDPS+, CP, IR}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{}}\\label{{fig.prof.lb}}
\\end{{subfigure}}
\\caption{{\\lid{{check: Bounds on the white-noise threshold $\\opt$:
\\subref{{fig.bounds.inst}} per instance; \\subref{{fig.prof.lb}} performance
profile of $\\lb_{{\\relx}}$. Abbreviations and findings in
\\Cref{{sec.aggregate}}.}}}}
\\label{{fig.profiles}}
\\end{{figure}}
"""
    p = os.path.join(out, "fig_bounds.tex")
    open(p, "w").write(tex)
    return p, len(rows)


# --------------------------------------------------------------------------
def fig_convergence(out, data, m=5):
    inst = load_instances(os.path.join(ROOT, "benchmark"))
    tdir = os.path.join(ROOT, "results", "main", "traces")
    panels = []
    for st, (name, mm) in sorted(inst.items(), key=lambda kv: display_name(kv[1][0])):
        if mm != m:
            continue
        series = {}
        for algo in ("CP", "IR"):
            src = os.path.join(tdir, f"{st}_{algo}.cp.csv")
            if not os.path.isfile(src):
                continue
            pts = []
            with open(src) as fh:
                for step, r in enumerate(csv.DictReader(fh)):
                    try:
                        v = float(r["ub_relx"])
                    except (KeyError, ValueError):
                        continue
                    if math.isfinite(v):
                        pts.append((step, v))
            if not pts:
                continue
            # Two corrections to the raw trace. `iter` restarts on every CP
            # call, so index by row. And IR makes several such calls, each
            # opening from a trivial bound, which draws as a jump back to 1;
            # the bound the algorithm actually holds is the running minimum,
            # which is also what glbub reports, so plot that.
            dst = f"conv_{name}_{algo}.dat"
            best = math.inf
            with open(os.path.join(data, dst), "w") as fh:
                fh.write("# step best_ub_relx\n")
                for s, v in pts:
                    best = min(best, v)
                    fh.write(f"{s} {best:.9f}\n")
            series[algo] = (dst, best)
        if series:
            panels.append((name, series))

    lo = min(v for _, s in panels for _, v in s.values()) - 0.004
    body = []
    for k, (name, s) in enumerate(panels):
        plots = "\n".join(
            f"\\addplot[{c}{st}] table[x index=0, y index=1, each nth point=8] {{plots/{f}}};"
            for (algo, (f, _)), c, st in zip(sorted(s.items()),
                                             ("sOne", "sTwo"), ("", ", dashed")))
        body.append(
            f"\\begin{{subfigure}}{{0.49\\textwidth}}\\centering\n"
            f"\\begin{{tikzpicture}}\\begin{{axis}}[vizbase, width=\\textwidth, height=3.9cm,\n"
            f"  title={{\\footnotesize {display_name(name).replace(chr(95), chr(92) + chr(95))}}},\n"
            f"  xlabel={{cutting-plane iteration}}, ylabel={{$\\ub_{{\\relx}}$}},\n"
            f"  xmin=0, ymin={lo:.3f}, ymax=1.005,\n"
            f"  scaled x ticks=false, /pgf/number format/1000 sep={{}},\n"
            f"  legend style={{at={{(0.97,0.95)}}, anchor=north east, legend columns=1}},\n"
            f"  every axis plot/.append style={{mark=none, line width=0.9pt}},\n]\n"
            f"{plots}\n\\legend{{CP, IR}}\n"
            f"\\end{{axis}}\\end{{tikzpicture}}\n\\end{{subfigure}}")

    tex = ("% generated by scripts/make_figures.py -- do not edit by hand\n"
           "\\begin{figure}[tbp]\n\\centering\n" + PREAMBLE + colours() + "\n"
           # pair the panels two per row; rstrip() takes a character set, not a
           # suffix, so the separator is placed between panels rather than
           # appended and trimmed
           + "\n".join(p + (r"\hfill" if i % 2 == 0 else "\n\n\\vspace{0.6em}\n")
                        if i < len(body) - 1 else p
                        for i, p in enumerate(body)) + "\n"
           "\\caption{\\lid{check: Best upper bound $\\ub_{\\relx}$ found so far, against\n"
           "cutting-plane iteration, for the $m=5$ instances under the common\n"
           "three-hour limit. Findings in \\Cref{sec.hard}.}}\n"
           "\\label{fig.conv.m5}\n\\end{figure}\n")
    p = os.path.join(out, "fig_convergence.tex")
    open(p, "w").write(tex)
    return p, len(panels)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--figure", choices=("bounds", "convergence", "all"), default="all")
    ap.add_argument("--out", default=ROOT, help="directory holding figures/ and plots/")
    a = ap.parse_args()
    fig = os.path.join(a.out, "figures")
    dat = os.path.join(a.out, "plots")
    os.makedirs(fig, exist_ok=True)
    os.makedirs(dat, exist_ok=True)
    if a.figure in ("bounds", "all"):
        p, n = fig_bounds(fig, dat)
        print(f"  wrote {p}  ({n} instances)")
    if a.figure in ("convergence", "all"):
        p, n = fig_convergence(fig, dat)
        print(f"  wrote {p}  ({n} panels)")


if __name__ == "__main__":
    main()
